# Generated by Django 5.2.4 on 2025-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contententry',
            name='collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
