# Generated by Django 5.2.4 on 2025-07-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contententry_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
