# Generated by Django 5.2.4 on 2025-07-27 15:17

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_categoriesentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contententry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 27, 15, 17, 9, 413161, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contententry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectsentry',
            name='categories',
            field=models.ManyToManyField(blank=True, to='content.categoriesentry'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
