# Generated by Django 5.2.4 on 2025-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contententry_created_at_contententry_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contententry',
            name='bricks_id',
            field=models.CharField(default='Bxh5zWHHrQnirVhwW99rB6', editable=False, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
